from waftools.plugin import plugin

def plugin_configure(conf):
    if not conf.check_cc(lib="gme", uselib_store="gme"):
        return False
    if not conf.check_cc(header_name="gme.h"):
        return False
    return True

configure, build = plugin('gme', configure=plugin_configure,
                          source=["gme_xform.c"], libs=["gme"])
